### PR TITLE
Pages - redesigning how information is presented

### PR DESCRIPTION
**Pull request by mtorres123**
@fengyanshi please accept the pull request from my pages branch. In this branch, I focused on redesigning the way information is presented on the wiki. For example, I added hyperlinks to journal articles in the theory sections to better guide interested readers; I separated example codes and input files from plain text into code blocks for easy reading; and I added more information regarding prerequisites needed for new users to run the model. Please review the changes on each page thoroughly, and notify me of any concerns, comments, or questions you have. I added a lot of sample makefiles to the examples pages. If anything fundamental about the format of these files will change in the future, please let me know and we will work towards making them user-friendly online. There are a few more additions/changes I would like to make to the wiki in a few weeks, such as redesigning some of the example cases I didn't finish. I will also be working with @malej on creating step-by-step tutorials for using FUNWAVE on the HPC portal, and will be adding these videos to the wiki. Thank you!

### CODE REVIEW

**Comment by fengyanshi** [comment]
thanks for the work

**Comment by fengyanshi** [comment]
@mtorres123 can you check if the page is correct after merging. I found some <<<HEAD appearing on the page. Thanks

**Comment by malej** [comment]
@fengyanshi @mtorres123 You have merge conflicts. See: https://fengyanshi.github.io/build/html/index.html

Meaning github was not able to resolve the conflicts on its own. So what it did was it went into every file that it could not resolve the conflict and put on lines: 

>>>>HEAD .   ..... some stuff here
<<<<< origin/master ....the same stuff here but slightly changed

and it's up to the user to go into all these files and pick which line should be correct and remove the incorrect line and the remaining >>>HEAD and <<<<origin/master

Let me know if you need more info/help.

**Comment by malej** [comment]
@fengyanshi did you execute a new: `make html` in the top directory of this repo? I am seeing old style stuff. @mtorres123 did not push `build` directory, so you need to compile html and push it back up to this repo

**Pull request merged**
